name: Publicar imagen Docker

on: 
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Hacer checkout del c贸digo
      - name: Checkout
        uses: actions/checkout@v2
      
      # 2. Configurar QEMU (emulaci贸n de arquitectura)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # 3. Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 4. Iniciar sesi贸n en Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Iniciar sesi贸n en GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHRC_TOKEN }}

      # 6. Construir y subir la imagen Docker
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            jesusn7/practica_7.1:latest
            ghcr.io/JesusN7/practica_7.1:latest
